• Example 1:
language: "en"
pipeline: "tensorflow_embedding"

• Example 2:
language: "en"
 pipeline:
 - name: "nlp_spacy"
 - name: "tokenizer_spacy"
 - name: "intent_entity_featurizer_regex"
 - name: "intent_featurizer_spacy"
 - name: "ner_crf"
 - name: "ner_synonyms"
 - name: "intent_classifier_sklearn"